[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; connect-src 'self' https:;"

[[redirects]]
  from = "/jira-api/*"
  to = "https://musinsa-oneteam.atlassian.net/:splat"
  status = 200
  force = true
  headers = {X-Atlassian-Token = "no-check"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
